### ISSUE TITLE
Typo: "running fafter script"

### ISSUE THREAD

**Issue by jerometwell** [jerometwell/pynonymizer#47] opened 2021-04-07 01:58 UTC
present in mssql, mysql and postgres providers, there's an additional "F" character being added in the log line for running before/after scripts. 

Remove it please!

```
            self.logger.info(f"Running f{title} script #{i} \"{script[:50]}\"")
```

**Comment by itsabhianant** [comment] 2021-04-07 02:36
Hi @jerometwell,

I got what your issue is and according to me the change you want to be made is on

1. [pynonymizer/pynonymizer/database/mssql/__init__.py /](https://github.com/jerometwell/pynonymizer/blob/master/pynonymizer/database/mssql/__init__.py) - line 173
2. [pynonymizer/pynonymizer/database/mysql/__init__.py /](https://github.com/jerometwell/pynonymizer/blob/master/pynonymizer/database/mysql/__init__.py) - line 64
3. [pynonymizer/pynonymizer/database/postgres/__init__.py /](https://github.com/jerometwell/pynonymizer/blob/master/pynonymizer/database/postgres/__init__.py) - line 62

---
As per my understanding you want this to be changed:

```py
 self.logger.info(f"Running f{title} script #{i} \"{script[:50]}\"")
```

to this:

```py
 self.logger.info(f"Running {title} script #{i} \"{script[:50]}\"")
```
---

If I got all your issues along with the solution correct please assign this issue to me. Or else please explain in brief what more changes you want me to make related to this issue. Also, it will be great if you assign me this issue after explaining what the issue is so that I can start working on it as soon as possible.

Best,
Abhishek

**Comment by jerometwell** [comment] 2021-04-07 02:42
Yeah that's what I was thinking 😇. I'll assign you the issue. Check out the CONTRIBUTING.md guide for general advice! 

PR when ready!

**Closed** 2021-04-08 12:17 UTC
Labels: good first issue
